name: Pull Docker Image on Remote Server

on:
  push:
    branches:
      - main

jobs:
  pull-docker-image:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install SSH Client
      run: sudo apt-get install -y openssh-client

    - name: Add SSH Key
      run: |
        echo "${{ secrets.SSH_PRIVATE_KEY }}" > key.pem
        chmod 600 key.pem
        eval $(ssh-agent -s)
        ssh-add key.pem

    - name: Add SSH Host Key
      run: |
        mkdir -p ~/.ssh
        ssh-keyscan -H 134.122.117.1 >> ~/.ssh/known_hosts

    - name: Pull Docker Image on Remote Server
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: |
        ssh -o StrictHostKeyChecking=no madhavi@134.122.117.1 << 'EOF'
          echo "${DOCKER_PASSWORD}" | docker login -u "${DOCKER_USERNAME}" --password-stdin
          docker pull ${{secrets.DOCKER_USERNAME}}/${{secrets.DOCKER_IMAGENAME}}:latest
        EOF
